spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/poc-customer-db
  kafka:
    bootstrap-servers: localhost:9092

server:
  servlet:
    context-path: /poc-customer
  port: 8088

logging.level.org.johnpaulkh.poc: DEBUG